# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd4f80b0f3a89c219f541c6fb170bcb420112f1397fd44962d315776124b8e894e25591155395abd2e1a39bb95d992fc432eeef4c8b2f814a9a9123324fa778

test:
  secret_key_base: fe2c543fbd1018267182a649d342955b6b60c0713a45cfd205a91930bc63a17e23bf3436ebc2ebf5bb56620e536210d74d1c9bfd52f6042914fada8149859ed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
